import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import './globals.css'

// components
import Navbar from './components/Navbar'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Real Estate Spot',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
