import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import './globals.css'

import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'

// components
import Navbar from './components/Navbar'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Real Estate Spot',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient({ cookies })
  const { data } = await supabase.auth.getSession()

  return (
    <html lang="en">
      <body className={raleway.className}>
        <Navbar user={data.session?.user} />
        {children}
      </body>
    </html>
  )
}
